### ISSUE TITLE
Show more testimonials Link does not work

### ISSUE THREAD

**Issue by gino2014** [tmhub/testimonials#4]
At Testimonials Page the "Show more testimonials" Link/Button does not work. It opens only new tab with the same testimonials site but without more testimonials.

**Comment by gino2014** [comment]
We are using Magento 1.9.2.4, Argento 1.7.3.1 and Testimonials 1.1.0

**Comment by roma84** [comment]
There were many changes in js and css files in new version, you need to clear merged js/css cache.

**Comment by gino2014** [comment]
Thanks for fast answer. It works now.
